# Generated by Django 4.2.4 on 2023-09-17 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('staffonly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('content', models.TextField(max_length=100, verbose_name='Отзыв')),
                ('publish', models.BooleanField(default=False, verbose_name='Состояние')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(default=5, verbose_name='Оценка')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staffonly.master', verbose_name='Мастер')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата записи')),
                ('appointment_time', models.TimeField(default='09:00', verbose_name='Дата и время записи')),
                ('publish', models.BooleanField(default=False, verbose_name='Состояние')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронировано')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffonly.master', verbose_name='Мастер')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга')),
            ],
        ),
    ]
