# Generated by Django 4.2.4 on 2023-09-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='services',
            new_name='service',
        ),
    ]
