# Generated by Django 4.2.4 on 2023-09-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(default='None', max_length=10, verbose_name='Email')),
                ('phone', models.CharField(default='None', max_length=10, verbose_name='Телефон')),
                ('first_name', models.CharField(default='None', max_length=10, verbose_name='Имя')),
                ('last_name', models.CharField(default='None', max_length=10, verbose_name='Фамилия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('publish', models.BooleanField(default=False, verbose_name='Состояние')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
